project_id = "mbxpkqhjapmhehdngfaj"

[functions.google-sheets]
verify_jwt = false

[functions.mercado-livre]
verify_jwt = false

[functions.shopee]
verify_jwt = false

[functions.tiny]
verify_jwt = false

[functions.ml-analyze-questions]
verify_jwt = false

[functions.ml-auto-answer]
verify_jwt = false

[functions.ml-fetch-questions]
verify_jwt = false

[functions.ml-manual-answer]
verify_jwt = false

[functions.ml-set-bot-mode]
verify_jwt = false

[functions.save-daily-snapshot]
enabled = true
verify_jwt = true
import_map = "./functions/save-daily-snapshot/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/save-daily-snapshot/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/save-daily-snapshot/*.html" ]
